spring.application.name=grpc
# Porta para as requisições REST (Postman)
server.port=8080

# Porta do Servidor gRPC
grpc.server.port=9090

# Cliente gRPC apontando para o servidor gRPC interno
grpc.client.local-grpc-server.address=static://localhost:9090
grpc.client.local-grpc-server.negotiation-type=plaintext